### ISSUE TITLE
Timed pause function works great. X/Y/Z park doesn't work at all.

### ISSUE THREAD

**Issue by ShewTheMighty** [philtgarner/pauseAtZprb#1]
I'm able to use your timed pause function. However, no matter what enter into the plug-in I get no park on the X/Y/Z. The head will lift the default 10m? on the Z, Which I believe is set up as a safety precaution in the plug-in itself but there is no movement after that. 

On the original plug in the park works but there is not pause.

Tried running them both in hopes that maybe they'd work in tangent but no luck just does the full park motion goes back to print location, then the next plug-in does it's thing. so that didn't help.

The reason I need the park function is to wipe the excess filament before resuming print.

**Comment by philtgarner** [comment]
OK. I'm not exactly an expert but I'll see what I can do. Could you provide some extra information to help me out:
- What version of Cura are you using?
- Have you tried it without any other plugins, if not what else are you using?
- What printer have you got?
- Could you post some G Code that doesn't work for you? Not necessarily the whole file but maybe just the section with the pause in it or a small sample print.

Cheers

**Comment by chesmith** [comment]
FYI, you're missing a \n at line 109, effectively causing the XY park instruction to get commented out in the resulting gcode.  After I added a \n it worked beautifully.  The Z park was working fine before I did this, though, as that's handled just before the ";PAUSING PRINT" comment.  I'm not sure what the OP might be facing there.  (I'm using Cura 15.04.3 on a Printrbot Play.)

If that's not clear, line 109 should state:
`f.write(";PAUSING PRINT\n");`

Thanks for putting this together!

**Comment by philtgarner** [comment]
Thanks @chesmith for pointing out the problem. Hopefully it fixes the bug @ShewTheMighty had. I don't really know why the problem didn't show up on my printer (Printrbot Simple 2014) but hopefully it's now a bit more reliable for others out there.
